CREATE TABLE COOKBOOK (
  GUID        VARCHAR(40)   NOT NULL,
  NAME        VARCHAR(100)  NOT NULL,
  DESCRIPTION VARCHAR(2000) NOT NULL,
  OWNER       VARCHAR(40)   NOT NULL
);

CREATE TABLE RECIPE (
  COOKBOOK_GUID VARCHAR(40)   NOT NULL,
  GUID          VARCHAR(40)   NOT NULL,
  NAME          VARCHAR(100)  NOT NULL,
  DESCRIPTION   VARCHAR(2000) NOT NULL,
  TYPE          VARCHAR(40)   NOT NULL
);

CREATE TABLE INGREDIENT (
  RECIPE_GUID VARCHAR(40)  NOT NULL,
  GUID        VARCHAR(40)  NOT NULL,
  QUANTITY    INTEGER      NOT NULL,
  UNIT        VARCHAR(40)  NOT NULL,
  NAME        VARCHAR(100) NOT NULL,
  TYPE        VARCHAR(100) NOT NULL
);
